# Generated by Django 5.1.5 on 2025-01-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('striming', '0003_alter_track_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.FloatField(),
        ),
    ]
