# Generated by Django 5.1.5 on 2025-01-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('striming', '0004_alter_track_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerne_name', models.CharField(max_length=30)),
            ],
        ),
    ]
